spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mysql?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    socketTimeout: 200
    minPoolSize: 4
    maxPoolSize: 50
server:
  port: 8089

  resources:
    static-locations: classpath:static/

    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
      cache: false

  mybatis:
    mapper-locations: classpath:mapping/UserMapper.xml
    type-aliases-package: xiaoxian.work.demo.bean

  logging:
    level:
      com:
        example:
          mapper: debug
